# ==============================
# 游댢 Configuraci칩n del Experimento
# ==============================

# N칰mero de 칠pocas para el entrenamiento
num_epochs: 10

# Tama침o del batch para entrenamiento y validaci칩n
batch_size: 2

# Directorio base de datos
data_dir_base: "ddbb_cropped"

# N칰mero de clases para la clasificaci칩n
num_classes: 7

# Aprendizaje
learning_rate: 1e-4

# Peso para el modelo preentrenado
pretrained_weights: "IMAGENET1K_V1"

# Frames por segundo para las carpetas
fps: 30

# Variantes de tie para iterar
ties:
  - "t_t"
  - "t_t0"
  - "t0_t"
  - "t0_t0"
